version: '2'
services:
  analytics:
    image: docker.wso2.com/apim-pattern6-am-analytics:2.1.0
    build:
      context: ../
      dockerfile: pattern-6/am-analytics/Dockerfile
    volumes:
      - ./am-analytics/carbon/repository/conf/datasources/analytics-datasources.xml:/mnt/wso2am-analytics-2.1.0/repository/conf/datasources/analytics-datasources.xml:ro
      - ./am-analytics/carbon/repository/conf/datasources/stats-datasources.xml:/mnt/wso2am-analytics-2.1.0/repository/conf/datasources/stats-datasources.xml:ro
    environment:
      - SLEEP=150
    ports:
      - "9448:9444"

  traffic-manager:
    image: docker.wso2.com/apim-pattern6-traffic-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-6/traffic-manager/Dockerfile
    volumes:
      - ./traffic-manager/carbon/repository/conf/datasources/master-datasources.xml:/mnt/wso2am-2.1.0/repository/conf/datasources/master-datasources.xml:ro
      - ./traffic-manager/carbon/repository/conf/registry.xml:/mnt/wso2am-2.1.0/repository/conf/registry.xml:ro
    environment:
      - SLEEP=60
    ports:
      - "9447:9443"
  keymanager:
    image: docker.wso2.com/apim-pattern6-keymanager:2.1.0
    build:
      context: ../
      dockerfile: pattern-6/keymanager/Dockerfile
    volumes:
      - ./keymanager/carbon/repository/conf/datasources/master-datasources.xml:/mnt/wso2am-2.1.0/repository/conf/datasources/master-datasources.xml:ro
      - ./keymanager/carbon/repository/conf/api-manager.xml:/mnt/wso2am-2.1.0/repository/conf/api-manager.xml:ro
      - ./keymanager/carbon/repository/conf/user-mgt.xml:/mnt/wso2am-2.1.0/repository/conf/user-mgt.xml:ro
    environment:
      - SLEEP=100
    ports:
      - "9443:9443"
      - "666:8243"

  gateway-manager:
    image: docker.wso2.com/apim-pattern6-gateway-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-6/gateway-manager/Dockerfile
    volumes:
      - ./gateway-manager/carbon/repository/conf/datasources/master-datasources.xml:/mnt/wso2am-2.1.0/repository/conf/datasources/master-datasources.xml:ro
      - ./gateway-manager/carbon/repository/conf/api-manager.xml:/mnt/wso2am-2.1.0/repository/conf/api-manager.xml:ro
      - ./gateway-manager/carbon/repository/conf/carbon.xml:/mnt/wso2am-2.1.0/repository/conf/carbon.xml:ro
    environment:
      - SLEEP=150
    ports:
      - "9444:9443"

  gateway-worker:
    image: docker.wso2.com/apim-pattern6-gateway-worker:2.1.0
    build:
      context: ../
      dockerfile: pattern-6/gateway-worker/Dockerfile
    volumes:
      - ./gateway-worker/carbon/repository/conf/datasources/master-datasources.xml:/mnt/wso2am-2.1.0/repository/conf/datasources/master-datasources.xml:ro
      - ./gateway-worker/carbon/repository/conf/api-manager.xml:/mnt/wso2am-2.1.0/repository/conf/api-manager.xml:ro
      - ./gateway-worker/carbon/repository/conf/carbon.xml:/mnt/wso2am-2.1.0/repository/conf/carbon.xml:ro
      - ./gateway-worker/carbon/repository/conf/log4j.properties:/mnt/wso2am-2.1.0/repository/conf/log4j.properties:ro
    environment:
      - SLEEP=200
    ports:
    - "8280:8280"
    - "8243:8243"
    links:
      - gateway-manager

  publisher-store:
    image: docker.wso2.com/apim-pattern6-publisher-store:2.1.0
    build:
      context: ../
      dockerfile: pattern-6/publisher-store/Dockerfile
    volumes:
      - ./publisher-store/carbon/repository/conf/datasources/master-datasources.xml:/mnt/wso2am-2.1.0/repository/conf/datasources/master-datasources.xml:ro
      - ./publisher-store/carbon/repository/conf/api-manager.xml:/mnt/wso2am-2.1.0/repository/conf/api-manager.xml:ro
      - ./publisher-store/carbon/repository/conf/carbon.xml:/mnt/wso2am-2.1.0/repository/conf/carbon.xml:ro
      - ./publisher-store/carbon/repository/conf/log4j.properties:/mnt/wso2am-2.1.0/repository/conf/log4j.properties:ro
      - ./publisher-store/carbon/repository/conf/jndi.properties:/mnt/wso2am-2.1.0/repository/conf/jndi.properties:ro
      - ./publisher-store/carbon/repository/conf/registry.xml:/mnt/wso2am-2.1.0/repository/conf/registry.xml:ro
      - ./publisher-store/carbon/repository/conf/user-mgt.xml:/mnt/wso2am-2.1.0/repository/conf/user-mgt.xml:ro
    environment:
      - SLEEP=230
    ports:
      - "9445:9443"